src/bin/brotli.rs, src/bit_reader/mod.rs, src/decode.rs, src/huffman/mod.rs, src/lib.rs, src/state.rs, src/transform.rs
those are mostly readability changes, but also replaces some counter vars
with `.enumerate()`, which *should* be equal performance-wise – but it's
a good idea to measure nonetheless. Also some pre-initialized mutable vars
could be directly initialized to their later value, which also probably
makes no perf difference (because LLVM will see right through it), but at
least may speed up the build a tiny bit. Also it's arguably more rustic.
=> fixed a number of clippy warnings

README.md
My colleague initially thought this was a decompressor-only library when she read the introduction. So I figured I'd make it clearer :)
=> Say "compressor" in the introduction

README.md
I noticed one of my applications wasn't compiling any longer after updating from brotli 1.0.8 to 2.3. I'm using the stream copy abstraction, and as such came back to the example in the README. Since the compiler told me that it now expects three instead of the four parameters given, the README seemed out of date. After I found the necessary fixes to my code to make in the source-code, I found it necessary to inform other developers of the change through the README.
While the example could still benefit from a more detailed explanation, at least now it is not incorrect.
=> fix of BrotliCompress example

Cargo.toml
Pointing twice to `README.md` doesn't seem necessary.
Of course, this means that the extracted doc needs to be documented :)
=> Cargo.toml: pointing to the extracted doc

src/enc/compress_fragment.rs
This removes spurious casting, unecessary nested braces, brackets, and dead code (eg. lines which are just 0i32). All tests pass as expected.
=> Clean up BrotliCompressFragmentFastImpl in compress_fragment.rs

Cargo.toml, examples/compress.rs, examples/decompress.rs, src/bin/catbrotli.rs, src/bin/integration_tests.rs, src/bin/test_broccoli.rs, src/bin/test_custom_dict.rs, src/bin/util.rs, src/concat/mod.rs, src/enc/backward_references/mod.rs, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/find_stride.rs, src/enc/histogram.rs, src/enc/input_pair.rs, src/enc/parameters.rs, src/enc/threading.rs, src/ffi/broccoli.rs, src/ffi/compressor.rs, src/ffi/multicompress/mod.rs, src/ffi/multicompress/test.rs
a recent refactor has reduced compression ratios for q9. This reverts the change and updates the system to remove warnings on new rust versions
=> Fix q9 compression

Cargo.toml, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/mod.rs, src/enc/prior_eval.rs, src/lib.rs
packed_simd is no longer maintained and does not compile.
=> Switch from packed_simd to packed_simd_2

src/ffi/compressor.rs
=> brotli: allow a NULL argument to BrotliEncoderDestroyInstance

src/enc/backward_references/mod.rs
It could be prettier, but I think it's better than no documentation.
=> Expose existing documentation for Brotli(HasherParams/EncoderParams) to rustdoc

src/enc/writer.rs
`BROTLI_OPERATION_FLUSH` must be re-tried until no more data is available as input and internal buffers are empty (this can take more than one call). Otherwise, the writer is left in a "flushing" state which will make further writes fail.
The documentation on how to use `BROTLI_OPERATION_FLUSH` (https://brotli.org/encode.html#aed2 , https://brotli.org/encode.html#a512) mentions the compressor should be called until it has no available input data and `BrotliEncoderHasMoreOutput()` returns false:
```
Under some circumstances (e.g. lack of output stream capacity) this operation would require several calls to BrotliEncoderCompressStream
[...]
Warning
When flushing and finishing, op should not change until operation is complete; input stream should not be swapped, reduced or extended as well. …
```
=> Fix partial flush on flush_or_close()

Cargo.toml, src/bin/validate.rs
As the version of sha2 that is packaged in debian is 0.10
=> upgrade the sha2 crate to 0.10

src/bin/brotli.rs
This section: https://github.com/dropbox/rust-brotli/blob/master/src/bin/brotli.rs#L638
And this section: https://github.com/dropbox/rust-brotli/blob/master/src/bin/brotli.rs#L666
Are identical (with the exception that one of them uses 2 spaces as indentation, and the other uses 4).
This PR removes the later one.
=> The -l parsing code is duplicated, remove the one that isn't reachable

Cargo.toml, c/Cargo.toml
Cleanup spacing and sorted dependencies in both Cargo.toml.  This is a precursor to upgrading to 2021 edition and many other linting changes
=> style: reformat Cargo.toml

.gitignore
Cargo.lock is neither checked in, nor ignored. This excludes it (usually lock is not needed for the libraries). It also excludes common IDEs and silly macOS files.
=> chore: .gitignore should exclude lock

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/dependabot.yml, Cargo.toml, c/.gitignore, justfile
* Add MSRV to Cargo.toml. The MSRV value will most likely change as the code is cleaned and uses newer language features.
up. It was computed using `cargo msrv`
* Add [justfile](https://just.systems/man/en/) with several commands to help with development
* Use GitHub CI to test everything using latest and MSRV Rust version. CI uses justfile so that it can be tested both in CI and locally.
* Add dependabot configuration and auto-accept - to make sure dependencies are regularly updated and tested
* Add semver checker to ensure that if there is a breaking change, the major/minor version of the crate reflects that
=> Add GitHub CI automation, MSRV, and `just` recipes

src/bin/integration_tests.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/cluster.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/literal_cost.rs, src/enc/metablock.rs, src/enc/util.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::assign_op_pattern
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/assign_op_pattern
See CI results in https://github.com/rust-brotli/rust-brotli/pull/12
=> Auto-fixed clippy::assign_op_pattern

src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/context_map_entropy.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/static_dict.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::precedence
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/precedence
See CI results in https://github.com/rust-brotli/rust-brotli/pull/17
=> Auto-fixed clippy::precedence

src/enc/brotli_bit_stream.rs, src/enc/find_stride.rs, src/enc/input_pair.rs, src/enc/ir_interpret.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::needless_lifetimes
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/needless_lifetimes
See CI results in https://github.com/rust-brotli/rust-brotli/pull/21
=> Auto-fixed clippy::needless_lifetimes

src/concat/mod.rs, src/enc/prior_eval.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::useless_conversion
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/useless_conversion
See CI results in https://github.com/rust-brotli/rust-brotli/pull/24
=> Auto-fixed clippy::useless_conversion

src/bin/brotli.rs, src/bin/util.rs, src/enc/input_pair.rs, src/enc/mod.rs, src/enc/threading.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::question_mark
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/question_mark
See CI results in https://github.com/rust-brotli/rust-brotli/pull/25
=> Auto-fixed clippy::question_mark

src/enc/brotli_bit_stream.rs, src/enc/mod.rs, src/ffi/compressor.rs, src/ffi/multicompress/mod.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::redundant_pattern_matching
```
See https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_pattern_matching
See CI results in https://github.com/rust-brotli/rust-brotli/pull/23
=> Auto-fixed clippy::redundant_pattern_matching

src/bin/util.rs, src/enc/backward_references/hash_to_binary_tree.rs, src/enc/interface.rs, src/enc/multithreading.rs, src/enc/singlethreading.rs, src/enc/threading.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::default_constructed_unit_structs
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/default_constructed_unit_structs
See CI results in https://github.com/rust-brotli/rust-brotli/pull/27
=> Auto-fixed clippy::default_constructed_unit_structs

src/concat/mod.rs, src/enc/context_map_entropy.rs
Note that this one might point to the underlying bug in the original implementation -- the masking of a `u8` values happens after casting it to a `u8`.
This was automatic change using these commands, and later excluded one that does not look that good.
```sh
cargo clippy --fix -- -A clippy::all -W clippy::identity_op
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/identity_op
See CI results in https://github.com/rust-brotli/rust-brotli/pull/31
=> Auto-fixed clippy::identity_op

src/enc/command.rs, src/enc/entropy_encode.rs, src/enc/input_pair.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::derivable_impls
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/derivable_impls
See CI results in https://github.com/rust-brotli/rust-brotli/pull/29
=> Auto-fixed clippy::derivable_impls

src/ffi/broccoli.rs, src/ffi/compressor.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::ptr_offset_with_cast
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/ptr_offset_with_cast
See CI results in https://github.com/rust-brotli/rust-brotli/pull/34
=> Auto-fixed clippy::ptr_offset_with_cast

src/bin/integration_tests.rs, src/bin/test_threading.rs, src/enc/compress_fragment.rs, src/enc/reader.rs, src/enc/static_dict.rs, src/enc/test.rs, src/enc/writer.rs
```sh
cargo clippy --fix -- -A clippy::all -W clippy::redundant_slicing
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_slicing
See CI results in https://github.com/rust-brotli/rust-brotli/pull/35
=> Auto-fixed clippy::redundant_slicing

src/concat/mod.rs, src/enc/find_stride.rs, src/enc/metablock.rs, src/enc/threading.rs
```sh
cargo clippy --fix -- -A clippy::all \
-W clippy::implicit_saturating_sub \
-W clippy::len_without_is_empty \
-W clippy::let_and_return \
-W clippy::manual_range_contains \
-W clippy::unused_unit
```
* https://rust-lang.github.io/rust-clippy/master/index.html#/implicit_saturating_sub
* https://rust-lang.github.io/rust-clippy/master/index.html#/len_without_is_empty
* https://rust-lang.github.io/rust-clippy/master/index.html#/let_and_return
* https://rust-lang.github.io/rust-clippy/master/index.html#/manual_range_contains
* https://rust-lang.github.io/rust-clippy/master/index.html#/unused_unit
See CI results in https://github.com/rust-brotli/rust-brotli/pull/36
=> Auto-fixed multiple small clippy lints

src/bin/brotli.rs, src/bin/integration_tests.rs, src/bin/test_broccoli.rs, src/bin/test_custom_dict.rs, src/bin/test_threading.rs, src/bin/tests.rs, src/bin/validate.rs, src/concat/mod.rs, src/enc/backward_references/test.rs, src/enc/bit_cost.rs, src/enc/block_split.rs, src/enc/brotli_bit_stream.rs, src/enc/fast_log.rs, src/enc/threading.rs, src/ffi/broccoli.rs
```
cargo clippy --fix -- -A clippy::all \
-W clippy::redundant_static_lifetimes \
-W clippy::redundant_pattern_matching \
-W clippy::from_over_into
```
Also, a few manual changes:
* allow `clippy::excessive_precision` to not warn. Not worth converting these.
* add manual `clippy::new_without_default` implementation
* a few more random ones that were discovered with `cargo clippy --fix`
=> A few simi-auto clippy lints

corrosion/backward_references_hq.rs, corrosion/backward_references_hq_safe.rs, src/enc/backward_references/benchmark.rs, src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/backward_references/test.rs, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/cluster.rs, src/enc/command.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/histogram.rs, src/enc/literal_cost.rs, src/enc/metablock.rs, src/enc/static_dict.rs, src/enc/utf8_util.rs
Whenever calling a function on a value, e.g. `value.wrapping_sub(1usize)`, there is almost never a need for specifying constant type.  The theoretical exception is if calling `foo<T>(&self, value: T)`, but I don't think there is a case like this here.
Another common case is a constant with type as an indexer - also never needed unless there is some magical implementation of the indexer trait.
Executed replacements:
```rust
.foo(123_usize)    -> .foo(123)
.foo(123 as usize) -> .foo(123)
[123_usize]        -> [123]
[(123_usize)]      -> [123]
[(123)]            -> [123]
[123_usize..       -> [123..
[(123_usize)..     -> [123..
```
```regex
(\.[a-z_]+)\((\d+)_?[ui][a-z0-9]*\)    -> $1($2)
(\.[a-z_]+)\((\d+) as [ui][a-z0-9]*\)  -> $1($2)
\[(\d+)_?[ui][a-z0-9]*\]               -> [$1] …
```
=> Simplify constant func params and index access

Cargo.toml, justfile, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/mod.rs, src/enc/prior_eval.rs, src/enc/worker_pool.rs, src/lib.rs
I made a fork of the packed_simd repo to fix the compilation issues (stdsimd has been renamed).
I then modified the dependency to point to that fork with the revision number (as suggested).
I am having trouble with the just file to add the nightly toolchain though.
=> Re-enable simd

src/bin/test_custom_dict.rs, src/bin/util.rs
* `write_one` in utils.rs uses `transformed_word.split_at(actual_copy_len).0;` in `interface::Command::Dict` -- this is a noop, can be safely removed, but may indicate there is a bug there.
* `test_custom_dict_for_multithreading` creates two vectors of 1 byte each, and they never grow - so clippy suggested to switch it to simple 1-element arrays. Not sure if this was intended, but this is a test...?
See CI run in https://github.com/rust-brotli/rust-brotli/pull/39
=> Detected suspicious code, needs feedback

justfile
This command is optional, and could be applied only once in a while. It shouldn't conflict with the regular stable `cargo fmt`, but it will keep the use statements more organized.
=> chore: add nightly fmt command

corrosion/backward_references_hq.rs, corrosion/backward_references_hq_safe.rs, src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/command.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/histogram.rs, src/enc/ir_interpret.rs, src/enc/metablock.rs, src/enc/static_dict.rs, src/enc/utf8_util.rs
There is no point in using type qualifier for bitshift param:
```
foo >> 2i32   ->   foo >> 2
```
Replacing
```
(<<|>>) (\d+)[ui](size|\d+)
```
with `$1 $2`
=> Remove explicit type for bitshifts

src/enc/backward_references/hq.rs, src/enc/block_splitter.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/static_dict.rs
All inlined usages of `value++` were converted to an unreadable
```rust
{
let _old = value;
value = value.wrapping_add(1);
_old
}
```
So I fixed them by simply moving the `++` portion to the following statement
Search string:
```
\.wrapping_add\(1\)\;\s*_
```
=> Fix inlined increments

src/ffi/compressor.rs, src/ffi/multicompress/mod.rs
This simplifies the code, keeping error handling more concise
=> Use method calls instead of match

src/enc/backward_references/mod.rs, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/cluster.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/metablock.rs, src/enc/static_dict.rs, src/enc/test.rs, src/enc/vectorization.rs
I used a very powerful tool [coccinelle](https://gitlab.inria.fr/coccinelle/coccinelleforrust) (its C version is used for Linux kernel refactorings).  Highly recommend installing it as it has a potential to simplify refactorings while not dealing with regex errors.
To install it, run
```sh
cargo install --git https://gitlab.inria.fr/coccinelle/coccinelleforrust
```
Afterward, create this file as `target/repl.cocci` with the following content. Using `target/` ensures that it will be ignored by git.
```diff
@@
@@
{
-    {
...
-    }
}
```
and run this command from the root of the repo:
```shell
cfr --apply -c target/repl.cocci src/
```
Afterwards, I manually reverted two macro_rules! changes -- those are the only ones that should continue having nested curlies.
=> Clean up some nested curly braces

src/enc/encode.rs, src/enc/metablock.rs
Use this replacement file as described in other recent PRs to replace boilerplate code.
Followed by `cargo fmt --all`
Some of these changes were in #158, but removed now.
<details>
<summary>replacement file content</summary>
```diff
@@
expression expr_r, expr_l;
@@
-{
-   let _rhs = expr_r;
-   let _lhs = &mut expr_l;
-   *_lhs *= _rhs;
+expr_l *= expr_r;
-}
@@
expression expr_r, expr_l, i, start, end;
@@
for i in start..end
{
-   let _rhs = expr_r;
-   let _lhs = &mut expr_l;
-   *_lhs += _rhs;
+expr_l += expr_r;
}
@@
expression expr_r, expr_l;
@@
-{
-   let _rhs = expr_r;
-   let _lhs = &mut expr_l;
-   *_lhs += _rhs;
+expr_l += expr_r;
-}
```
</details>
=> Simplify non-wrapping += and *=

src/enc/backward_references/hq.rs
here `i` can never exceed a relatively small `BROTLI_NUM_COMMAND_SYMBOLS`, no need for wrapping_add
=> Tiny manual fix

src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs
Ran `cargo clippy -- -A clippy::all -W clippy::no_effect` and fixed them.
Mostly removing statements like `0i32;`
=> Remove unused values

src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs
Move two `init` functions into BackwardMatchMut, moving one of them from another file.
Note that `init_backward` was not public, so in order to use it but not expose outside, it was marked as `pub(crate)`
=> Use `self` with BackwardMatchMut fn

src/enc/backward_references/hq.rs, src/enc/bit_cost.rs, src/enc/brotli_bit_stream.rs, src/enc/cluster.rs, src/enc/entropy_encode.rs, src/enc/static_dict.rs
Manually fix several for loops
I used this replacement, and then went through each and reasoned if wrapping can ever happen (mostly it cannot, e.g. -1 is ok if for loop starts at 1)
When reviewing, make sure to use "ignore blanks" because lots of code was only de-indented.
```diff
@@
expression idx, start, end;
@@
-   idx = start;
-   while idx < end
+   for idx in start..end
{
{
...
}
-        idx = idx.wrapping_add(1);
}
@@
expression idx, start, end;
@@
-   idx = start;
-   while idx <= end
+   for idx in start..=end
{
{
...
}
-        idx = idx.wrapping_add(1);
}
```
=> Manually fix several for loops

src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/backward_references/test.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/command.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/find_stride.rs, src/enc/input_pair.rs, src/enc/interface.rs, src/enc/ir_interpret.rs, src/enc/metablock.rs, src/enc/prior_eval.rs, src/enc/static_dict_lut.rs, src/enc/stride_eval.rs, src/enc/utf8_util.rs, src/enc/weights.rs
When a hex number is used with bit operations, it tends to be less readable as it gets longer.  Hex numbers should have each 4 digits separated by a `_`, and separate from the type - so that we can easily see if the number group has 3 or 4 digits.
In some cases I also removed the type qualifier - as it is auto-detected and not needed.
=> Make hex numbers more readable

src/bin/brotli.rs, src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/command.rs, src/enc/encode.rs, src/enc/histogram.rs, src/enc/interface.rs, src/enc/metablock.rs, src/lib.rs
`CommandDistanceContext` was consolidated because it had identical code
Use `hide whitespace changes` when reviewing
=> Use proper `self` for Command and related

src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/encode.rs
Hide whitespace when viewing changes.
Several giant blocks of code are never used. If they are still needed, we should use conditional compilation, and add it to the CI to avoid bitrot.
=> Remove dead code blocks

src/enc/backward_references/hq.rs
The nested loop is only executed once, so made the code much more readable and clearer by removing it. Inside the loop, the if statement had to be inverted.
Use `hide whitespace changes` when reviewing
=> Remove unused loop

src/enc/backward_references/hq.rs
The nested loop is only executed once, so made the code much more readable and clearer by removing it.
Note that wrapping add was not needed because `j` is limited to 16.
Use `hide whitespace` when reviewing
=> Remove unused loop (2)

src/enc/backward_references/hq.rs
The nested loop is only executed once, so made the code much more readable and clearer by removing it.
Also, cleaned up the rest of the SetCost function
=> Remove unused loop (3)

src/enc/backward_references/hash_to_binary_tree.rs
Make sure to hide whitespace changes when reviewing.
=> Simplify loop in StoreAndFindMatchesH10

src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/test.rs, src/enc/brotli_bit_stream.rs, src/enc/context_map_entropy.rs, src/enc/encode.rs, src/enc/ir_interpret.rs, src/enc/mod.rs, src/enc/multithreading.rs, src/enc/prior_eval.rs, src/enc/singlethreading.rs, src/enc/stride_eval.rs, src/enc/test.rs, src/enc/threading.rs, src/enc/vectorization.rs, src/enc/worker_pool.rs, src/ffi/alloc_util.rs, src/ffi/broccoli.rs, src/ffi/compressor.rs, src/ffi/multicompress/mod.rs, src/ffi/multicompress/test.rs, src/lib.rs
The `use foo` is no longer allowed when `foo` is part of the current crate. This has been the standard ever since 2018 edition.  `use crate::foo` is a preferred method.
* Use search/replace to replace:
* `use enc::` -> `use crate::enc::`
* `use concat::` -> `use crate::concat::`
* `use VERSION` -> `use crate::VERSION`
* ` ::interface` to ` crate::interface` (both strings start with a space)
* Run `just fmt2` to reorg use statements to new groups.
=> Switch to `use crate::` for local decl

src/enc/compress_fragment.rs
Remove a few unused brackets. Note that `'break15` loop had two breaks with label, and one without - I guess it was just an accident that the last one didn't have a label (line 757 after the change at `if IsMatch(&input_ptr[...`)?
=> Minor compress_fragment cleanup

src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/brotli_bit_stream.rs, src/enc/command.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/encode.rs, src/enc/entropy_encode.rs, src/enc/threading.rs
There are a few publicly visible functions that should also be using a `bool` type.  In order not to cause an API change, I created a crate-visible variants so that we can remove them in the next major release. In the meantime, users will see a deprecation warning IF they are using these functions (most likely they are not) - but if they are, they will let us know to keep them public.
Note a few extra `FIXME` -- these I think we should fix when making a breaking change, but not just yet because they are harder to do in a backward-compatible way
=> Use bools instead of i32s (second part)

src/bin/validate.rs, src/enc/backward_references/benchmark.rs, src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/backward_references/mod.rs, src/enc/backward_references/test.rs, src/enc/block_split.rs, src/enc/block_splitter.rs, src/enc/brotli_bit_stream.rs, src/enc/cluster.rs, src/enc/combined_alloc.rs, src/enc/context_map_entropy.rs, src/enc/encode.rs, src/enc/find_stride.rs, src/enc/metablock.rs, src/enc/prior_eval.rs, src/enc/reader.rs, src/enc/stride_eval.rs, src/enc/threading.rs, src/enc/writer.rs
Introduce several helper memory allocation functions to reduce boilerplate code.  This will help in the future to further simplify allocation, esp when alloc module becomes part of stdlib.  The helper functions allow far simpler usage with a generic type as the first param.
I began with this replacement:
```
\<([a-zA-Z0-9_]+) as Allocator\<([a-zA-Z0-9_]+)\>\>\:\:AllocatedMemory\:\:default\(\s*\)
```
with
```
alloc_default::<$2, $1>()
```
In a few cases, I was able to use `alloc.alloc_cell(...)` directly (compiler was able to figure out which type to use automatically).
Afterward, found all conditional allocations and replaced them with `alloc_if(condition, ...)`, and fixed the imports
=> Simplify mem cell alloc usage

src/enc/backward_references/hash_to_binary_tree.rs, src/enc/backward_references/hq.rs, src/enc/bit_cost.rs, src/enc/block_splitter.rs, src/enc/cluster.rs, src/enc/compress_fragment.rs, src/enc/compress_fragment_two_pass.rs, src/enc/context_map_entropy.rs, src/enc/encode.rs, src/enc/histogram.rs, src/enc/literal_cost.rs, src/enc/metablock.rs, src/enc/prior_eval.rs, src/enc/util.rs
* Remove where not needed (implied)
* Add parenthesis to make casting explicitly clear
* Add `use` statement to make it cleaner
* Cleanup logic in the bit_cost.rs - BitsEntropy, using `max`
=> Manually cleanup floatX types

src/enc/brotli_bit_stream.rs
Apparently `best_speed_log` was never tested - it does not compile due to a missing format placeholder. I think this is what it meant, but feel free to fix it in other way (or delete entirely?)
=> Fix CI bug with best_speed_log

.github/workflows/ci.yml, Cargo.toml, src/enc/mod.rs
Fix CI once again - this time it will be tested in every branch too (so will work in the fork repos).  Also, there is a compilation issue requiring MSRV to be 1.59
=> fix ci semver compat, enable in branches

src/concat/mod.rs, src/enc/backward_references/test.rs, src/enc/command.rs, src/enc/interface.rs, src/enc/static_dict.rs, src/ffi/multicompress/mod.rs
Some modules were missing conditional test-only compilation.  In a few files, move `mod test {...}` to the end of the file (per convention)
=> Add conditional cfg(test) to modules

src/enc/bit_cost.rs, src/enc/encode.rs
`ShannonEntropy` is currently exposed publicly. In my last PR its signature changed. In order to avoid another major release, add a deprecated wrapper for it until we are ready to migrate to the new major version.
This allows us to make patch releases because no functionality has been changed yet.
=> Fix CI: avoid breaking semver

Cargo.toml
This commit adds an explicit `package.include` section to the `Cargo.toml` file to only include relevant rust code into the final package. This decreases the size of the uploaded tar-ball from 1.3 Mb to ~700kb and it also decreases the number of included files from ~140 to ~70. Finally it removes any possibly unwanted binary data from the uploaded package, which follows security best-practices.
Fixes #220
=> Add an explicit include section to the `Cargo.toml`

Cargo.toml
When the contents of the published crate were minimized in 4b059e6081386238c764d11140605a5514da30f5, the file `LICENSE.BSD-3-Clause` was omitted from the list of files to include.
=> Fix missing LICENSE.BSD-3-Clause in published crate
